engines:
  coverage:
    enabled: true
    exclude_paths:
      - app/forms/*
      - app/models/*
      - conf/**/*
      - public/**/*
      - test/*
      - 'scalastyle-config.xml'

exclude_paths:
  - test/*