engines:
  coverage:
    enabled: true
    exclude_paths:
      - app/forms/*
      - app/models/*
      - app/rest/*
      - conf/**/*
      - public/**/*
      - test/*
      - scalastyle-config.xml