language: scala
scala:
   - 2.11.11
jdk:
  - oraclejdk8
script:
  - sbt clean coverage test
after_success:
  - coverageExcludedPackages := "app\\.forms\\.*;app\\.models\\.*;app\\.rest\\.*;conf\\.*;public\\.*;test\\.*"
  - sbt coverageReport
  - sbt codacyCoverage

