language: scala
scala:
   - 2.11.11
jdk:
  - oraclejdk8
script:
  - coverageExcludedPackages := "app\\.forms.*;app\\.models.*;app\\.rest.*;conf.*;public.*;test.*"
  - sbt clean coverage test
after_success:
  - sbt coverageReport
  - sbt codacyCoverage